<?php
require_once __DIR__ . '/config.php';
$action = $_GET['action'] ?? (is_admin() ? 'dashboard' : 'login');
$msg = flash('msg'); $mt = flash('msg_type') ?: 'success';

if ($action === 'logout') { session_destroy(); redirect('admin.php?action=login'); }

if ($action === 'login' && $_SERVER['REQUEST_METHOD'] === 'POST') {
    $u = trim($_POST['username'] ?? ''); $p = $_POST['password'] ?? '';
    try { $st = db()->prepare("SELECT * FROM users WHERE username=? LIMIT 1"); $st->execute([$u]); $usr = $st->fetch();
    if ($usr && password_verify($p, $usr['password'])) { $_SESSION['frost_admin'] = true; $_SESSION['admin_user'] = $usr['username']; $_SESSION['admin_id'] = $usr['id']; redirect('admin.php?action=dashboard'); }
    $msg = '用户名或密码错误'; $mt = 'error'; } catch (Exception $e) { $msg = '数据库连接失败'; $mt = 'error'; }
}

if ($action === 'post-save' && $_SERVER['REQUEST_METHOD'] === 'POST') { require_admin();
    $id = intval($_POST['id'] ?? 0); $title = trim($_POST['title'] ?? ''); $content = $_POST['content'] ?? ''; $excerpt = trim($_POST['excerpt'] ?? '');
    $cat_id = intval($_POST['category_id'] ?: 0) ?: null; $type = in_array($_POST['type'] ?? '', ['post','sharing']) ? $_POST['type'] : 'post';
    $status = in_array($_POST['status'] ?? '', ['draft','published']) ? $_POST['status'] : 'draft'; $feat = intval($_POST['is_featured'] ?? 0);
    $cover = $_POST['existing_cover'] ?? ''; if (!empty($_FILES['cover_image']['name'])) { $u = upload_image($_FILES['cover_image']); if ($u) $cover = $u; }
    $sv = slug_en($title ?: 'post-' . time()); $bs = $sv; $c = 1; while (true) { $ch = db()->prepare("SELECT COUNT(*) FROM posts WHERE slug=? AND id!=?"); $ch->execute([$sv, $id]); if ((int)$ch->fetchColumn() === 0) break; $sv = $bs . '-' . (++$c); }
    $pub = ($status === 'published') ? date('Y-m-d H:i:s') : null;
    if ($id > 0) { db()->prepare("UPDATE posts SET title=?,slug=?,content=?,excerpt=?,cover_image=?,category_id=?,type=?,status=?,is_featured=?,published_at=IF(published_at IS NOT NULL,published_at,?) WHERE id=?")->execute([$title,$sv,$content,$excerpt,$cover,$cat_id,$type,$status,$feat,$pub,$id]); set_flash('msg','文章已更新'); }
    else { db()->prepare("INSERT INTO posts (title,slug,content,excerpt,cover_image,category_id,type,status,is_featured,published_at) VALUES (?,?,?,?,?,?,?,?,?,?)")->execute([$title,$sv,$content,$excerpt,$cover,$cat_id,$type,$status,$feat,$pub]); set_flash('msg','文章已发布'); }
    set_flash('msg_type','success'); redirect('admin.php?action=posts'); }

if ($action === 'post-delete' && $_SERVER['REQUEST_METHOD'] === 'POST') { require_admin(); db()->prepare("DELETE FROM posts WHERE id=?")->execute([intval($_POST['id'] ?? 0)]); set_flash('msg','已删除'); set_flash('msg_type','success'); redirect('admin.php?action=posts'); }
if ($action === 'post-toggle' && $_SERVER['REQUEST_METHOD'] === 'POST') { require_admin(); $id = intval($_POST['id'] ?? 0); if ($id > 0) { $c = db()->prepare("SELECT status FROM posts WHERE id=?"); $c->execute([$id]); $r = $c->fetch(); if ($r) { $n = $r['status'] === 'published' ? 'draft' : 'published'; $pub = ($n === 'published') ? date('Y-m-d H:i:s') : null; db()->prepare("UPDATE posts SET status=?,published_at=IF(?='published',COALESCE(published_at,?),published_at) WHERE id=?")->execute([$n,$n,$pub,$id]); set_flash('msg',$n==='published'?'已发布':'已转草稿'); set_flash('msg_type','success'); }} redirect('admin.php?action=posts'); }

if ($action === 'cat-save' && $_SERVER['REQUEST_METHOD'] === 'POST') { require_admin(); $id = intval($_POST['id'] ?? 0); $name = trim($_POST['name'] ?? ''); $sl = slug_en($name) ?: 'cat-' . time();
    if ($id > 0) { db()->prepare("UPDATE categories SET name=?,slug=?,description=?,color=?,sort_order=? WHERE id=?")->execute([$name,$sl,trim($_POST['description']??''),$_POST['color']??'#3b6ef5',intval($_POST['sort_order']??0),$id]); } else { db()->prepare("INSERT INTO categories (name,slug,description,color,sort_order) VALUES (?,?,?,?,?)")->execute([$name,$sl,trim($_POST['description']??''),$_POST['color']??'#3b6ef5',intval($_POST['sort_order']??0)]); }
    set_flash('msg','分类已保存'); set_flash('msg_type','success'); redirect('admin.php?action=categories'); }
if ($action === 'cat-delete' && $_SERVER['REQUEST_METHOD'] === 'POST') { require_admin(); db()->prepare("DELETE FROM categories WHERE id=?")->execute([intval($_POST['id'] ?? 0)]); set_flash('msg','已删除'); set_flash('msg_type','success'); redirect('admin.php?action=categories'); }

if ($action === 'settings-save' && $_SERVER['REQUEST_METHOD'] === 'POST') { require_admin();
    foreach (['blog_name','blog_tagline','blog_desc','author_name','author_bio','author_role','social_github','social_twitter','social_email','icp_filing'] as $f) { if (isset($_POST[$f])) set_setting($f, trim($_POST[$f])); }
    set_setting('wish_enabled', isset($_POST['wish_enabled']) ? '1' : '0');
    set_flash('msg','设置已保存'); set_flash('msg_type','success'); redirect('admin.php?action=settings'); }

if ($action === 'change-pass' && $_SERVER['REQUEST_METHOD'] === 'POST') { require_admin(); $old = $_POST['old_pass'] ?? ''; $new = $_POST['new_pass'] ?? '';
    if (strlen($new) < 6) { set_flash('msg','新密码至少 6 位'); set_flash('msg_type','error'); } else { $st = db()->prepare("SELECT password FROM users WHERE id=?"); $st->execute([$_SESSION['admin_id']]); $r = $st->fetch(); if ($r && password_verify($old, $r['password'])) { db()->prepare("UPDATE users SET password=? WHERE id=?")->execute([password_hash($new, PASSWORD_DEFAULT), $_SESSION['admin_id']]); set_flash('msg','密码已修改'); set_flash('msg_type','success'); } else { set_flash('msg','原密码错误'); set_flash('msg_type','error'); }} redirect('admin.php?action=settings'); }
?>
<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>摸鱼博客 · 后台</title>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&display=swap" rel="stylesheet">
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐟</text></svg>">
<?php if (in_array($action, ['post-new','post-edit'])): ?><link href="https://cdn.quilljs.com/1.3.7/quill.snow.css" rel="stylesheet"><?php endif; ?>
<style>
:root{--p:#3b6ef5;--pd:#2a56d4;--gb:rgba(255,255,255,0.55);--gbl:rgba(255,255,255,0.7);--bs:rgba(77,120,255,0.1);--t1:#1a1d2e;--t2:#5a6278;--t3:#8b93a8;--ok:#059669;--er:#dc2626;--wn:#d97706;--rl:20px;--rm:12px;--rs:8px;--rp:16px}
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}body{font-family:'DM Sans',-apple-system,'PingFang SC','Microsoft YaHei',sans-serif;font-size:13px;line-height:1.6;color:var(--t1);background:linear-gradient(160deg,#eef3ff,#e4edff 50%,#f0f4ff);min-height:100vh}
body::before{content:'';position:fixed;top:-25%;left:-18%;width:60%;height:60%;background:radial-gradient(circle,rgba(77,120,255,0.07),transparent 65%);pointer-events:none;z-index:0}body::after{content:'';position:fixed;bottom:-20%;right:-12%;width:55%;height:55%;background:radial-gradient(circle,rgba(90,140,255,0.05),transparent 60%);pointer-events:none;z-index:0}
.glass{background:var(--gb);backdrop-filter:blur(40px) saturate(1.6);-webkit-backdrop-filter:blur(40px) saturate(1.6);border:1px solid var(--gbl);border-radius:var(--rl);box-shadow:0 0 0 1px var(--bs),inset 0 1px 0 rgba(255,255,255,0.9),inset 0 -1px 0 rgba(0,0,0,0.02),inset 0 40px 60px -40px rgba(255,255,255,0.35),0 2px 8px rgba(77,120,255,0.04),0 8px 32px rgba(77,120,255,0.06),0 20px 60px rgba(77,120,255,0.05)}
.btn{display:inline-flex;align-items:center;justify-content:center;gap:6px;padding:9px 20px;font-size:12.5px;font-weight:600;font-family:inherit;border:none;border-radius:var(--rm);cursor:pointer;text-decoration:none;transition:all .2s;line-height:1.4}.btn-p{background:linear-gradient(135deg,var(--p),var(--pd));color:#fff;box-shadow:0 2px 8px rgba(59,110,245,0.2)}.btn-p:hover{box-shadow:0 4px 16px rgba(59,110,245,0.35);transform:translateY(-1px)}.btn-g{background:rgba(255,255,255,0.3);color:var(--t1);border:1px solid rgba(77,120,255,0.06)}.btn-g:hover{background:rgba(255,255,255,0.5)}.btn-d{background:rgba(220,38,38,0.07);color:var(--er);border:1px solid rgba(220,38,38,0.08)}.btn-d:hover{background:rgba(220,38,38,0.14)}.btn-s{background:rgba(5,150,105,0.08);color:var(--ok);border:1px solid rgba(5,150,105,0.08)}.sm{padding:6px 14px;font-size:11.5px;border-radius:var(--rs)}
label{display:block;font-size:12px;font-weight:600;color:var(--t2);margin-bottom:5px}input[type=text],input[type=password],input[type=email],input[type=url],input[type=number],input[type=color],select,textarea{width:100%;padding:9px 14px;font-size:12.5px;font-family:inherit;border:1px solid rgba(77,120,255,0.06);border-radius:var(--rm);background:rgba(255,255,255,0.35);color:var(--t1);outline:none;transition:all .2s}input:focus,select:focus,textarea:focus{border-color:rgba(59,110,245,0.35);background:rgba(255,255,255,0.65);box-shadow:0 0 0 3px rgba(59,110,245,0.08)}textarea{resize:vertical;min-height:90px}select{cursor:pointer}input[type=color]{width:50px;height:38px;padding:4px;cursor:pointer}input[type=checkbox]{width:16px;height:16px;accent-color:var(--p);cursor:pointer}.fg{margin-bottom:16px}.fr{display:grid;grid-template-columns:1fr 1fr;gap:14px}.fh{font-size:11px;color:var(--t3);margin-top:4px}
.alert{padding:10px 16px;border-radius:var(--rm);font-size:12.5px;margin-bottom:16px}.alert-s{background:rgba(5,150,105,0.07);color:var(--ok);border:1px solid rgba(5,150,105,0.1)}.alert-e{background:rgba(220,38,38,0.07);color:var(--er);border:1px solid rgba(220,38,38,0.1)}
.dt{width:100%;border-collapse:collapse}.dt th{font-size:11px;font-weight:600;color:var(--t3);text-align:left;padding:10px 14px;border-bottom:1px solid rgba(77,120,255,0.06);text-transform:uppercase;letter-spacing:.5px}.dt td{padding:12px 14px;border-bottom:1px solid rgba(77,120,255,0.03);font-size:13px;vertical-align:middle}.dt tr:last-child td{border-bottom:none}.dt tr:hover td{background:rgba(59,110,245,0.015)}
.tag{display:inline-flex;padding:3px 10px;font-size:11px;font-weight:600;border-radius:var(--rp)}.tag-d{background:rgba(217,119,6,0.08);color:var(--wn)}.tag-p{background:rgba(5,150,105,0.08);color:var(--ok)}.tag-post{background:rgba(59,110,245,0.08);color:var(--p)}.tag-sharing{background:rgba(139,92,246,0.08);color:#8b5cf6}
.al{display:flex;min-height:100vh;position:relative;z-index:1}.sb{width:240px;min-height:100vh;padding:24px 14px;display:flex;flex-direction:column;position:fixed;top:0;left:0;bottom:0;background:rgba(255,255,255,0.4);backdrop-filter:blur(40px) saturate(1.6);-webkit-backdrop-filter:blur(40px) saturate(1.6);border-right:1px solid rgba(255,255,255,0.45);z-index:50}.sb-brand{font-size:16px;font-weight:700;padding:0 12px 20px;display:flex;align-items:center;gap:8px;border-bottom:1px solid rgba(77,120,255,0.06);margin-bottom:16px}.sb-brand .f{font-size:18px}.sb-nav{flex:1;display:flex;flex-direction:column;gap:2px}.sb-nav a{display:flex;align-items:center;gap:10px;padding:10px 14px;font-size:13px;font-weight:500;color:var(--t2);text-decoration:none;border-radius:var(--rm);transition:all .2s}.sb-nav a:hover{background:rgba(59,110,245,0.06);color:var(--t1)}.sb-nav a.ac{background:rgba(59,110,245,0.1);color:var(--p);font-weight:600}.sb-nav .ic{width:18px;text-align:center;font-size:14px;opacity:.7}.sb-ft{padding-top:16px;border-top:1px solid rgba(77,120,255,0.06);display:flex;flex-direction:column;gap:4px}.sb-ft a{font-size:12px;color:var(--t3);text-decoration:none;padding:6px 14px;border-radius:var(--rs);transition:all .2s}.sb-ft a:hover{color:var(--t1)}
.mn{flex:1;margin-left:240px;padding:28px 32px;min-width:0}.ph{display:flex;align-items:center;justify-content:space-between;margin-bottom:28px;flex-wrap:wrap;gap:12px}.ph h1{font-size:20px;font-weight:700}.ph p{font-size:12.5px;color:var(--t3);margin-top:2px}
.sg2{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-bottom:28px}.sc{padding:20px;text-align:center}.sc .si{font-size:18px;opacity:.3;margin-bottom:8px}.sc .sn{font-size:26px;font-weight:700;color:var(--p)}.sc .sl{font-size:11.5px;color:var(--t3);margin-top:4px}
.cc{padding:0;overflow:hidden;margin-bottom:20px}.cch{display:flex;align-items:center;justify-content:space-between;padding:14px 20px;border-bottom:1px solid rgba(77,120,255,0.04)}.cch h2{font-size:13.5px;font-weight:700}.ccb{padding:20px}.ccb.flat{padding:0}
.ql-toolbar.ql-snow{border:1px solid rgba(77,120,255,0.06)!important;border-radius:var(--rm) var(--rm) 0 0;background:rgba(255,255,255,0.4)!important}.ql-container.ql-snow{border:1px solid rgba(77,120,255,0.06)!important;border-top:none!important;border-radius:0 0 var(--rm) var(--rm);min-height:320px;font-family:'DM Sans',-apple-system,'PingFang SC',sans-serif!important;font-size:14px!important;background:rgba(255,255,255,0.5)}.ql-editor{min-height:280px;line-height:1.8}.ql-snow .ql-stroke{stroke:var(--t2)!important}.ql-snow .ql-fill{fill:var(--t2)!important}.ql-snow .ql-picker{color:var(--t2)!important}
@keyframes fu{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:translateY(0)}}.fi{opacity:0;animation:fu .4s cubic-bezier(.16,1,.3,1) forwards}
.lp{min-height:100vh;display:flex;align-items:center;justify-content:center;position:relative;z-index:1}.lc{width:380px;max-width:92vw;padding:40px 36px;text-align:center}.lc h1{font-size:20px;font-weight:700;margin-bottom:6px}.lc .sub{font-size:12.5px;color:var(--t2);margin-bottom:28px}.lc .lico{font-size:40px;margin-bottom:16px;display:block}
@media(max-width:1024px){.sg2{grid-template-columns:repeat(2,1fr)}}
@media(max-width:768px){.sb{width:100%;min-height:auto;position:relative;flex-direction:row;flex-wrap:wrap;padding:12px;gap:4px;align-items:center}.al{flex-direction:column}.mn{margin-left:0;padding:20px 16px}.sb-brand{padding:0 10px 0;border-bottom:none;margin-bottom:0;font-size:15px}.sb-nav{flex-direction:row;flex-wrap:wrap;gap:2px;flex:1}.sb-nav a{padding:6px 10px;font-size:11.5px}.sb-nav .ic{display:none}.sb-ft{display:none}.fr{grid-template-columns:1fr}}
</style></head><body>

<?php if ($action === 'login'): ?>
<div class="lp"><div class="lc glass fi"><span class="lico">🐟</span><h1>摸鱼博客</h1><p class="sub">管理后台 · 低调摸鱼</p><?php if($msg):?><div class="alert alert-<?=e($mt)?>"><?=e($msg)?></div><?php endif;?>
<form method="POST" action="admin.php?action=login"><div class="fg" style="text-align:left"><label>用户名</label><input type="text" name="username" required autofocus></div><div class="fg" style="text-align:left"><label>密码</label><input type="password" name="password" required></div><button type="submit" class="btn btn-p" style="width:100%;padding:12px">🐟 登录</button></form>
<a href="index.php" style="display:block;margin-top:20px;font-size:12px;color:var(--t3);text-decoration:none">← 回到博客</a></div></div>

<?php else: require_admin(); ?>
<div class="al">
<aside class="sb"><div class="sb-brand"><span class="f">🐟</span>摸鱼博客</div>
<nav class="sb-nav">
<a href="admin.php?action=dashboard" class="<?=$action==='dashboard'?'ac':''?>"><span class="ic">◆</span>仪表盘</a>
<a href="admin.php?action=posts" class="<?=in_array($action,['posts','post-new','post-edit'])?'ac':''?>"><span class="ic">📝</span>文章</a>
<a href="admin.php?action=categories" class="<?=$action==='categories'?'ac':''?>"><span class="ic">📂</span>分类</a>
<a href="admin.php?action=wishes" class="<?=$action==='wishes'?'ac':''?>"><span class="ic">⭐</span>许愿墙</a>
<a href="admin.php?action=settings" class="<?=$action==='settings'?'ac':''?>"><span class="ic">⚙</span>设置</a>
</nav>
<div class="sb-ft"><a href="index.php" target="_blank">查看博客 ↗</a><a href="admin.php?action=logout" style="color:var(--er)">退出登录</a></div></aside>

<main class="mn">
<?php if($msg):?><div class="alert alert-<?=e($mt)?> fi"><?=e($msg)?></div><?php endif;?>

<?php switch ($action):

case 'dashboard':
$tp=count_posts('published');$td=count_posts('draft');$tv=get_total_views();$cc=count(get_categories());$wc=(int)@db()->query("SELECT COUNT(*) FROM wishes")->fetchColumn();
$rec=db()->query("SELECT p.id,p.title,p.slug,p.status,p.view_count,p.updated_at,c.name AS cat_name FROM posts p LEFT JOIN categories c ON p.category_id=c.id ORDER BY p.updated_at DESC LIMIT 8")->fetchAll();?>
<div class="ph fi"><div><h1>📊 仪表盘</h1><p>欢迎回来，<?=e($_SESSION['admin_user']??'Admin')?></p></div><a href="admin.php?action=post-new" class="btn btn-p">+ 写点什么</a></div>
<div class="sg2 fi"><div class="sc glass"><div class="si">📝</div><div class="sn"><?=$tp?></div><div class="sl">已发布</div></div><div class="sc glass"><div class="si">📋</div><div class="sn"><?=$td?></div><div class="sl">草稿</div></div><div class="sc glass"><div class="si">👁</div><div class="sn"><?=number_format($tv)?></div><div class="sl">总阅读</div></div><div class="sc glass"><div class="si">⭐</div><div class="sn"><?=$wc?></div><div class="sl">留言</div></div></div>
<div class="cc glass fi"><div class="cch"><h2>最近更新</h2><a href="admin.php?action=posts" class="btn btn-g sm">全部</a></div><div class="ccb flat"><?php if(empty($rec)):?><p style="padding:32px;text-align:center;color:var(--t3)">暂无内容</p><?php else:?><table class="dt"><thead><tr><th>标题</th><th>状态</th><th>阅读</th><th>更新</th></tr></thead><tbody><?php foreach($rec as $r):?><tr><td><a href="admin.php?action=post-edit&id=<?=$r['id']?>" style="color:var(--t1);text-decoration:none;font-weight:600"><?=e(truncate($r['title'],40))?></a></td><td><span class="tag <?=$r['status']==='published'?'tag-p':'tag-d'?>"><?=$r['status']==='published'?'已发布':'草稿'?></span></td><td style="font-size:12px;color:var(--t3)"><?=$r['view_count']?></td><td style="font-size:12px;color:var(--t3)"><?=time_ago($r['updated_at'])?></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></div><?php break;

case 'posts':
$all=db()->query("SELECT p.*,c.name AS cat_name FROM posts p LEFT JOIN categories c ON p.category_id=c.id ORDER BY p.is_featured DESC,p.created_at DESC")->fetchAll();?>
<div class="ph fi"><div><h1>📝 文章管理</h1><p>共 <?=count($all)?> 篇</p></div><a href="admin.php?action=post-new" class="btn btn-p">+ 新建</a></div>
<div class="cc glass fi"><div class="ccb flat"><?php if(empty($all)):?><p style="padding:40px;text-align:center;color:var(--t3)">空空如也</p><?php else:?><table class="dt"><thead><tr><th>标题</th><th>类型</th><th>分类</th><th>状态</th><th>★</th><th>阅读</th><th>操作</th></tr></thead><tbody><?php foreach($all as $p):?><tr><td><a href="admin.php?action=post-edit&id=<?=$p['id']?>" style="color:var(--t1);text-decoration:none;font-weight:600"><?=e(truncate($p['title'],28))?></a></td><td><span class="tag tag-<?=$p['type']?>"><?=$p['type']==='post'?'文章':'分享'?></span></td><td style="font-size:12px;color:var(--t3)"><?=e($p['cat_name']??'—')?></td><td><span class="tag <?=$p['status']==='published'?'tag-p':'tag-d'?>"><?=$p['status']==='published'?'已发布':'草稿'?></span></td><td><?=$p['is_featured']?'★':''?></td><td style="font-size:12px;color:var(--t3)"><?=$p['view_count']?></td><td><div style="display:flex;gap:5px"><a href="admin.php?action=post-edit&id=<?=$p['id']?>" class="btn btn-g sm">编辑</a><form method="POST" action="admin.php?action=post-toggle" style="display:inline"><input type="hidden" name="id" value="<?=$p['id']?>"><button class="btn <?=$p['status']==='published'?'btn-s':'btn-g'?> sm"><?=$p['status']==='published'?'下架':'发布'?></button></form><form method="POST" action="admin.php?action=post-delete" onsubmit="return confirm('确定？')" style="display:inline"><input type="hidden" name="id" value="<?=$p['id']?>"><button class="btn btn-d sm">删除</button></form></div></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></div><?php break;

case 'post-new': case 'post-edit':
$edit=null;if($action==='post-edit'){$eid=intval($_GET['id']??0);$st=db()->prepare("SELECT * FROM posts WHERE id=?");$st->execute([$eid]);$edit=$st->fetch();if(!$edit)redirect('admin.php?action=posts');}$cats=get_categories();?>
<div class="ph fi"><h1><?=$edit?'编辑文章':'新建文章'?></h1><a href="admin.php?action=posts" class="btn btn-g">← 返回</a></div>
<form method="POST" action="admin.php?action=post-save" enctype="multipart/form-data" class="fi">
<?php if($edit):?><input type="hidden" name="id" value="<?=$edit['id']?>"><?php endif;?><?php if($edit&&$edit['cover_image']):?><input type="hidden" name="existing_cover" value="<?=e($edit['cover_image'])?>"><?php endif;?>
<div style="display:grid;grid-template-columns:1fr 280px;gap:20px;align-items:start"><div><div class="cc glass"><div class="ccb"><div class="fg"><input type="text" name="title" value="<?=e($edit['title']??'')?>" required placeholder="文章标题" style="font-size:18px;font-weight:700;padding:14px 16px"></div><div class="fg"><div id="eq"></div><textarea name="content" id="ech" style="display:none"><?=e($edit['content']??'')?></textarea></div><div class="fg"><label>摘要</label><textarea name="excerpt" rows="3"><?=e($edit['excerpt']??'')?></textarea></div></div></div></div>
<div><div class="cc glass" style="margin-bottom:14px"><div class="ccb"><div class="fg"><label>状态</label><select name="status"><option value="draft" <?=($edit['status']??'')==='draft'?'selected':''?>>草稿</option><option value="published" <?=($edit['status']??'draft')==='published'?'selected':''?>>发布</option></select></div><div class="fg"><label>类型</label><select name="type"><option value="post" <?=($edit['type']??'')==='post'?'selected':''?>>文章</option><option value="sharing" <?=($edit['type']??'')==='sharing'?'selected':''?>>分享</option></select></div><div class="fg"><label>分类</label><select name="category_id"><option value="">无分类</option><?php foreach($cats as $c):?><option value="<?=$c['id']?>" <?=($edit['category_id']??'')==$c['id']?'selected':''?>><?=e($c['name'])?></option><?php endforeach;?></select></div><div class="fg" style="display:flex;align-items:center;gap:8px"><input type="checkbox" name="is_featured" value="1" id="ft" <?=($edit['is_featured']??0)?'checked':''?>><label for="ft" style="margin-bottom:0;cursor:pointer">精选文章</label></div><button type="submit" class="btn btn-p" style="width:100%"><?=$edit?'💾 更新':'💾 保存'?></button></div></div>
<div class="cc glass"><div class="ccb"><label style="margin-bottom:10px">封面图片</label><?php if($edit&&$edit['cover_image']):?><div style="margin-bottom:10px;border-radius:var(--rs);overflow:hidden"><img src="<?=UPLOAD_URL.'/'.e($edit['cover_image'])?>" style="width:100%;display:block"></div><?php endif;?><input type="file" name="cover_image" accept="image/*" style="font-size:12px"><p class="fh">JPG/PNG/WebP</p></div></div></div></form>
<script src="https://cdn.quilljs.com/1.3.7/quill.min.js"></script><script>var q=new Quill('#eq',{theme:'snow',placeholder:'开始创作…',modules:{toolbar:[[{header:[2,3,false]}],['bold','italic','underline','strike'],[{list:'ordered'},{list:'bullet'}],['blockquote','code-block'],['link','image'],[{color:[]},{background:[]}],['clean']]}});var h=document.getElementById('ech');if(h.value)q.root.innerHTML=h.value;document.querySelector('form').addEventListener('submit',function(){h.value=q.root.innerHTML;});</script><?php break;

case 'categories':
$ac=get_categories();$ed=null;if(isset($_GET['edit'])){$eid=intval($_GET['edit']);foreach($ac as $c){if($c['id']===$eid){$ed=$c;break;}}}
?>
<div class="ph fi"><h1>📂 分类管理</h1></div>
<div style="display:grid;grid-template-columns:1fr 320px;gap:20px;align-items:start"><div class="cc glass fi"><div class="ccb flat"><?php if(empty($ac)):?><p style="padding:32px;text-align:center;color:var(--t3)">暂无分类</p><?php else:?><table class="dt"><thead><tr><th>名称</th><th>颜色</th><th>文章</th><th>排序</th><th>操作</th></tr></thead><tbody><?php foreach($ac as $c):?><tr><td style="font-weight:600"><?=e($c['name'])?></td><td><span style="display:inline-block;width:14px;height:14px;border-radius:4px;background:<?=e($c['color'])?>"></span></td><td style="font-size:12px;color:var(--t3)"><?=$c['post_count']?></td><td style="font-size:12px;color:var(--t3)"><?=$c['sort_order']?></td><td><div style="display:flex;gap:5px"><a href="admin.php?action=categories&edit=<?=$c['id']?>" class="btn btn-g sm">编辑</a><form method="POST" action="admin.php?action=cat-delete" onsubmit="return confirm('删除？')" style="display:inline"><input type="hidden" name="id" value="<?=$c['id']?>"><button class="btn btn-d sm">删除</button></form></div></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></div>
<div class="cc glass fi"><div class="cch"><h2><?=$ed?'编辑':'新建'?>分类</h2></div><div class="ccb"><form method="POST" action="admin.php?action=cat-save"><?php if($ed):?><input type="hidden" name="id" value="<?=$ed['id']?>"><?php endif;?><div class="fg"><label>名称</label><input type="text" name="name" value="<?=e($ed['name']??'')?>" required></div><div class="fg"><label>描述</label><textarea name="description" rows="2"><?=e($ed['description']??'')?></textarea></div><div class="fr"><div class="fg"><label>颜色</label><input type="color" name="color" value="<?=e($ed['color']??'#3b6ef5')?>"></div><div class="fg"><label>排序</label><input type="number" name="sort_order" value="<?=intval($ed['sort_order']??0)?>"></div></div><button type="submit" class="btn btn-p" style="width:100%"><?=$ed?'更新':'创建'?></button><?php if($ed):?><a href="admin.php?action=categories" class="btn btn-g" style="width:100%;margin-top:8px">取消</a><?php endif;?></form></div></div></div><?php break;

case 'wishes':
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_POST['act'])){require_admin();$wid=intval($_POST['id']??0);if($wid){
    if($_POST['act']==='hide'){db()->prepare("UPDATE wishes SET status='hidden' WHERE id=?")->execute([$wid]);set_flash('msg','已隐藏');}
    elseif($_POST['act']==='show'){db()->prepare("UPDATE wishes SET status='visible' WHERE id=?")->execute([$wid]);set_flash('msg','已恢复');}
    elseif($_POST['act']==='del'){db()->prepare("DELETE FROM wishes WHERE id=?")->execute([$wid]);set_flash('msg','已删除');}
    set_flash('msg_type','success');redirect('admin.php?action=wishes');}}
$aw=db()->query("SELECT * FROM wishes ORDER BY created_at DESC LIMIT 100")->fetchAll();?>
<div class="ph fi"><h1>⭐ 留言许愿管理</h1><p>共 <?=count($aw)?> 条</p></div>
<div class="cc glass fi"><div class="ccb flat"><?php if(empty($aw)):?><p style="padding:32px;text-align:center;color:var(--t3)">暂无留言</p><?php else:?><table class="dt"><thead><tr><th>昵称</th><th>类型</th><th>内容</th><th>状态</th><th>时间</th><th>操作</th></tr></thead><tbody><?php foreach($aw as $w):?><tr><td style="font-weight:600"><span style="display:inline-block;width:24px;height:24px;border-radius:50%;background:<?=e($w['avatar_color'])?>;color:#fff;font-size:11px;text-align:center;line-height:24px;margin-right:6px;vertical-align:middle"><?=mb_substr($w['nickname'],0,1)?></span><?=e($w['nickname'])?></td><td><span class="tag" style="<?=$w['wish_type']==='wish'?'background:rgba(217,119,6,0.08);color:#d97706':'background:rgba(59,110,245,0.08);color:#3b6ef5'?>"><?=$w['wish_type']==='wish'?'⭐ 许愿':'💬 留言'?></span></td><td style="max-width:300px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap"><?=e(truncate($w['content'],50))?></td><td><span class="tag <?=$w['status']==='visible'?'tag-p':'tag-d'?>"><?=$w['status']==='visible'?'可见':'隐藏'?></span></td><td style="font-size:12px;color:var(--t3)"><?=time_ago($w['created_at'])?></td><td><div style="display:flex;gap:4px"><form method="POST" style="display:inline"><input type="hidden" name="id" value="<?=$w['id']?>"><input type="hidden" name="act" value="<?=$w['status']==='visible'?'hide':'show'?>"><button class="btn btn-g sm"><?=$w['status']==='visible'?'隐藏':'恢复'?></button></form><form method="POST" onsubmit="return confirm('删除？')" style="display:inline"><input type="hidden" name="id" value="<?=$w['id']?>"><input type="hidden" name="act" value="del"><button class="btn btn-d sm">删除</button></form></div></td></tr><?php endforeach;?></tbody></table><?php endif;?></div></div><?php break;

case 'settings':
$ai=db()->prepare("SELECT * FROM users WHERE id=?");$ai->execute([$_SESSION['admin_id']]);$ai=$ai->fetch();?>
<div class="ph fi"><h1>⚙ 系统设置</h1></div>
<div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;align-items:start">
<div class="cc glass fi"><div class="cch"><h2>博客信息</h2></div><div class="ccb"><form method="POST" action="admin.php?action=settings-save"><div class="fg"><label>博客名称</label><input type="text" name="blog_name" value="<?=e(setting('blog_name'))?>"></div><div class="fg"><label>标语</label><input type="text" name="blog_tagline" value="<?=e(setting('blog_tagline'))?>"></div><div class="fg"><label>描述</label><textarea name="blog_desc" rows="3"><?=e(setting('blog_desc'))?></textarea></div><div class="fg"><label>作者名称</label><input type="text" name="author_name" value="<?=e(setting('author_name'))?>"></div><div class="fg"><label>角色头衔</label><input type="text" name="author_role" value="<?=e(setting('author_role'))?>"></div><div class="fg"><label>作者简介</label><textarea name="author_bio" rows="3"><?=e(setting('author_bio'))?></textarea></div><div class="fg"><label>GitHub</label><input type="url" name="social_github" value="<?=e(setting('social_github'))?>"></div><div class="fg"><label>Twitter</label><input type="url" name="social_twitter" value="<?=e(setting('social_twitter'))?>"></div><div class="fg"><label>邮箱</label><input type="email" name="social_email" value="<?=e(setting('social_email'))?>"></div><div class="fg"><label>ICP 备案</label><input type="text" name="icp_filing" value="<?=e(setting('icp_filing'))?>"></div>
<div class="fg" style="display:flex;align-items:center;gap:10px;margin-top:20px;padding-top:16px;border-top:1px solid rgba(77,120,255,0.06)"><input type="checkbox" name="wish_enabled" value="1" id="we" <?=setting('wish_enabled','1')==='1'?'checked':''?>><label for="we" style="margin-bottom:0;cursor:pointer">开启留言许愿</label></div>
<button type="submit" class="btn btn-p" style="width:100%">保存设置</button></form></div></div>
<div>
<div class="cc glass fi"><div class="cch"><h2>账户安全</h2></div><div class="ccb"><form method="POST" action="admin.php?action=change-pass"><div class="fg"><label>当前用户</label><input type="text" value="<?=e($ai['username']??'')?>" disabled style="opacity:.5"></div><div class="fg"><label>原密码</label><input type="password" name="old_pass" required></div><div class="fg"><label>新密码</label><input type="password" name="new_pass" required minlength="6" placeholder="至少 6 位"></div><button type="submit" class="btn btn-p" style="width:100%">修改密码</button></form></div></div>
<div class="cc glass fi" style="margin-top:20px"><div class="cch"><h2>系统信息</h2></div><div class="ccb"><div style="font-size:12px;color:var(--t3);line-height:2.2"><div>PHP <?=phpversion()?></div><div>MySQL <?=@db()->query("SELECT VERSION()")->fetchColumn()?></div><div>时间 <?=date('Y-m-d H:i:s')?></div><div>上传 <?=(is_dir(UPLOAD_DIR)&&is_writable(UPLOAD_DIR))?'<span style="color:var(--ok)">✓</span>':'<span style="color:var(--er)">✗</span>'?></div><div>摸鱼博客 v1.0</div></div></div></div>
</div></div><?php break;

default: redirect('admin.php?action=dashboard'); endswitch;?>
</main></div><?php endif;?></body></html>