# ┌────────────────────────────────────────────────────────────────────┐
# │  🐟  摸鱼博客 · MoyuBlogs                                          │
# │  📦  仓库地址 https://github.com/moyu678/moyu-blogs                │
# │  💰  赞助地址 http://ifdian.net/a/jiadian                          │
# └────────────────────────────────────────────────────────────────────┘

<?php
require_once __DIR__ . '/config.php';

$uri = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$bd = rtrim(dirname($_SERVER['SCRIPT_NAME']), '/');
if ($bd && $bd !== '/' && strpos($uri, $bd) === 0) $uri = substr($uri, strlen($bd));
$seg = array_values(array_filter(explode('/', trim($uri, '/')), 'strlen'));
if (!empty($seg) && preg_match('/^index\.php$/i', $seg[0])) array_shift($seg);

$page = 'landing'; $slug = ''; $cat = ''; $paged = max(1, intval($_GET['p'] ?? 1)); $q = trim($_GET['q'] ?? '');

if (!empty($seg)) {
    $s0 = $seg[0];
    if ($s0 === 'blog') {
        $page = 'blog'; $i = 1;
        if (isset($seg[$i]) && $seg[$i] !== 'page') { $cat = $seg[$i]; $i++; }
        if (isset($seg[$i], $seg[$i + 1]) && $seg[$i] === 'page') $paged = max(1, intval($seg[$i + 1]));
    } elseif ($s0 === 'post' && isset($seg[1])) { $page = 'post'; $slug = $seg[1]; }
    elseif ($s0 === 'sharing') $page = 'sharing';
    elseif ($s0 === 'about') $page = 'about';
    elseif ($s0 === 'wish') $page = 'wish';
}
if (isset($_GET['page'])) $page = $_GET['page'];
if (isset($_GET['slug'])) $slug = $_GET['slug'];

$pp = 9; $off = ($paged - 1) * $pp;
if ($page === 'post' && $slug) { try { db()->prepare("UPDATE posts SET view_count=view_count+1 WHERE slug=? AND status='published'")->execute([$slug]); } catch (Exception $e) {} }
$cats = get_categories();
$bn = setting('blog_name', BLOG_NAME); $bt = setting('blog_tagline', BLOG_TAGLINE);
$an = setting('author_name', '摸鱼人'); $ab = setting('author_bio', ''); $ar = setting('author_role', '开发者 · 创作者 · 专业摸鱼人'); $icp = setting('icp_filing', '');
?>
<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title><?php if($page==='post'&&$slug){$pt=get_post($slug);echo ($pt?e($pt['title']).' — ':'').e($bn);}elseif($page==='blog')echo'博客 — '.e($bn);elseif($page==='sharing')echo'分享 — '.e($bn);elseif($page==='about')echo'关于 — '.e($bn);elseif($page==='wish')echo'许愿 — '.e($bn);else echo e($bn).' — '.e($bt);?></title>
<link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400;9..40,500;9..40,600;9..40,700&display=swap" rel="stylesheet">
<link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>🐟</text></svg>">
<style>
:root{--primary:#3b6ef5;--primary-dark:#2a56d4;--primary-light:#6b8cff;--bg:linear-gradient(160deg,#eef3ff 0%,#e4edff 50%,#f0f4ff 100%);--gb:rgba(255,255,255,0.55);--gbl:rgba(255,255,255,0.7);--bs:rgba(77,120,255,0.1);--t1:#1a1d2e;--t2:#5a6278;--t3:#8b93a8;--ok:#059669;--er:#dc2626;--wn:#d97706;--rl:20px;--rm:12px;--rs:8px;--rp:16px}
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}body{font-family:'DM Sans',-apple-system,'PingFang SC','Microsoft YaHei',sans-serif;font-size:13.5px;line-height:1.7;color:var(--t1);background:var(--bg);min-height:100vh;overflow-x:hidden}
.atmo{position:fixed;inset:0;pointer-events:none;z-index:0;overflow:hidden}.orb{position:absolute;border-radius:50%}.o1{top:-12%;left:-15%;width:55vw;height:55vw;background:radial-gradient(circle,rgba(77,120,255,0.08),transparent 65%);animation:of1 25s ease-in-out infinite}.o2{bottom:-15%;right:-12%;width:50vw;height:50vw;background:radial-gradient(circle,rgba(90,140,255,0.06),transparent 60%);animation:of2 30s ease-in-out infinite}.o3{top:18%;right:12%;width:320px;height:320px;background:radial-gradient(circle,rgba(77,120,255,0.05),transparent 70%);animation:of3 20s ease-in-out infinite}.o4{bottom:22%;left:8%;width:260px;height:260px;background:radial-gradient(circle,rgba(100,150,255,0.05),transparent 70%);animation:of4 22s ease-in-out infinite}
@keyframes of1{0%,100%{transform:translate(0,0)}50%{transform:translate(3vw,4vh)}}@keyframes of2{0%,100%{transform:translate(0,0)}50%{transform:translate(-4vw,-3vh)}}@keyframes of3{0%,100%{transform:translate(0,0)}33%{transform:translate(-20px,30px)}66%{transform:translate(15px,-20px)}}@keyframes of4{0%,100%{transform:translate(0,0)}50%{transform:translate(25px,-15px)}}
.glass{background:var(--gb);backdrop-filter:blur(40px) saturate(1.6);-webkit-backdrop-filter:blur(40px) saturate(1.6);border:1px solid var(--gbl);border-radius:var(--rl);box-shadow:0 0 0 1px var(--bs),inset 0 1px 0 rgba(255,255,255,0.9),inset 0 -1px 0 rgba(0,0,0,0.02),inset 0 40px 60px -40px rgba(255,255,255,0.35),0 2px 8px rgba(77,120,255,0.04),0 8px 32px rgba(77,120,255,0.06),0 20px 60px rgba(77,120,255,0.05)}
.nav{position:fixed;top:0;left:0;right:0;z-index:100;height:64px;padding:0 32px;display:flex;align-items:center;justify-content:space-between;background:rgba(255,255,255,0.4);backdrop-filter:blur(40px) saturate(1.6);-webkit-backdrop-filter:blur(40px) saturate(1.6);border-bottom:1px solid rgba(255,255,255,0.45);transition:all .3s}.nav.sc{background:rgba(255,255,255,0.65);box-shadow:0 4px 20px rgba(77,120,255,0.05)}.nb{font-size:17px;font-weight:700;color:var(--t1);text-decoration:none;display:flex;align-items:center;gap:8px;letter-spacing:.3px}.nb .f{font-size:20px}.nl{display:flex;align-items:center;gap:4px}.nl a{padding:7px 16px;font-size:13px;font-weight:500;color:var(--t2);text-decoration:none;border-radius:var(--rp);transition:all .2s}.nl a:hover,.nl a.ac{color:var(--primary);background:rgba(59,110,245,0.06)}.ns{position:relative}.ns svg{position:absolute;left:11px;top:50%;transform:translateY(-50%);width:14px;height:14px;color:var(--t3);pointer-events:none}.ns input{width:190px;padding:7px 12px 7px 32px;font-size:12.5px;font-family:inherit;background:rgba(255,255,255,0.35);border:1px solid rgba(77,120,255,0.06);border-radius:var(--rp);color:var(--t1);outline:none;transition:all .25s}.ns input:focus{width:250px;background:rgba(255,255,255,0.65);border-color:rgba(59,110,245,0.35)}.ns input::placeholder{color:var(--t3)}
.btn{display:inline-flex;align-items:center;justify-content:center;gap:6px;padding:10px 24px;font-size:13px;font-weight:600;font-family:inherit;border:none;border-radius:var(--rm);cursor:pointer;text-decoration:none;transition:all .2s;line-height:1.4}.btn-p{background:linear-gradient(135deg,var(--primary),var(--primary-dark));color:#fff;box-shadow:0 2px 8px rgba(59,110,245,0.2),inset 0 1px 0 rgba(255,255,255,0.12)}.btn-p:hover{box-shadow:0 4px 16px rgba(59,110,245,0.35);transform:translateY(-1px)}.btn-g{background:rgba(255,255,255,0.3);color:var(--t1);border:1px solid rgba(77,120,255,0.06);backdrop-filter:blur(8px)}.btn-g:hover{background:rgba(255,255,255,0.5)}.sm{padding:6px 14px;font-size:12px;border-radius:var(--rs)}
.tag{display:inline-flex;padding:4px 12px;font-size:11.5px;font-weight:600;border-radius:var(--rp);letter-spacing:.3px}.ts{padding:3px 10px;font-size:10.5px}
.pc{border-radius:var(--rl);overflow:hidden;background:var(--gb);backdrop-filter:blur(40px) saturate(1.6);-webkit-backdrop-filter:blur(40px) saturate(1.6);border:1px solid var(--gbl);box-shadow:0 0 0 1px var(--bs),inset 0 1px 0 rgba(255,255,255,0.9),inset 0 -1px 0 rgba(0,0,0,0.02),inset 0 40px 60px -40px rgba(255,255,255,0.35),0 2px 8px rgba(77,120,255,0.04),0 8px 32px rgba(77,120,255,0.06),0 20px 60px rgba(77,120,255,0.05);transition:transform .2s,box-shadow .25s;opacity:0;animation:ci .5s cubic-bezier(.16,1,.3,1) forwards}.pc:nth-child(2){animation-delay:.06s}.pc:nth-child(3){animation-delay:.12s}.pc:nth-child(4){animation-delay:.18s}.pc:nth-child(5){animation-delay:.24s}.pc:nth-child(6){animation-delay:.3s}.pc:hover{transform:translateY(-4px);box-shadow:0 0 0 1px var(--bs),inset 0 1px 0 rgba(255,255,255,0.9),inset 0 -1px 0 rgba(0,0,0,0.02),inset 0 40px 60px -40px rgba(255,255,255,0.35),0 4px 12px rgba(77,120,255,0.06),0 12px 40px rgba(77,120,255,0.1),0 24px 70px rgba(77,120,255,0.08)}@keyframes ci{from{opacity:0;transform:translateY(16px)}to{opacity:1;transform:translateY(0)}}
.cc{aspect-ratio:16/9;overflow:hidden;position:relative}.cc img{width:100%;height:100%;object-fit:cover;transition:transform .4s}.pc:hover .cc img{transform:scale(1.04)}.ccp{width:100%;height:100%;display:flex;align-items:center;justify-content:center;background:linear-gradient(135deg,rgba(59,110,245,0.04),rgba(59,110,245,0.1));font-size:36px;color:rgba(59,110,245,0.12)}.cb{padding:20px}.cm{display:flex;align-items:center;gap:8px;margin-bottom:10px;flex-wrap:wrap}.ct{font-size:17px;font-weight:700;line-height:1.45;margin-bottom:8px;letter-spacing:.3px}.ct a{color:var(--t1);text-decoration:none;transition:color .2s}.ct a:hover{color:var(--primary)}.ce{font-size:13px;color:var(--t2);line-height:1.65;margin-bottom:14px;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.cf{display:flex;align-items:center;justify-content:space-between;font-size:11.5px;color:var(--t3)}.cf .v{display:flex;align-items:center;gap:3px}.cf .v svg{width:13px;height:13px}
.bg{display:grid;grid-template-columns:repeat(3,1fr);gap:24px}.bg .pc.ft{grid-column:span 2}.bg .pc.ft .cc{aspect-ratio:2/1}.bg .pc.ft .ct{font-size:20px}
.fb{display:flex;align-items:center;gap:8px;margin-bottom:28px;flex-wrap:wrap}.fp{padding:7px 18px;font-size:12.5px;font-weight:500;font-family:inherit;border:1px solid rgba(77,120,255,0.06);border-radius:var(--rp);background:rgba(255,255,255,0.3);color:var(--t2);cursor:pointer;backdrop-filter:blur(8px);text-decoration:none;transition:all .2s}.fp:hover,.fp.ac{background:var(--primary);color:#fff;border-color:var(--primary)}
.pg{display:flex;align-items:center;justify-content:center;gap:8px;margin-top:40px}.pg a,.pg span{display:inline-flex;align-items:center;justify-content:center;min-width:38px;height:38px;padding:0 12px;font-size:13px;font-weight:500;font-family:inherit;border:1px solid rgba(77,120,255,0.06);border-radius:var(--rm);background:rgba(255,255,255,0.3);color:var(--t2);text-decoration:none;backdrop-filter:blur(8px);transition:all .2s;cursor:pointer}.pg a:hover,.pg span.cur{background:var(--primary);color:#fff;border-color:var(--primary)}.pg span.cur{font-weight:700}
.hero{min-height:100vh;display:flex;align-items:center;justify-content:center;text-align:center;position:relative;padding:80px 24px 60px}.hc{max-width:560px;padding:48px 44px;opacity:0;animation:fu .6s cubic-bezier(.16,1,.3,1) .1s forwards}.ha{width:80px;height:80px;border-radius:50%;margin:0 auto 24px;background:linear-gradient(135deg,var(--primary),var(--primary-light));display:flex;align-items:center;justify-content:center;font-size:36px;border:3px solid rgba(255,255,255,0.8);box-shadow:0 6px 24px rgba(59,110,245,0.15)}.hero h1{font-size:28px;font-weight:700;letter-spacing:.5px;margin-bottom:10px}.ht{font-size:15px;color:var(--t2);margin-bottom:28px;line-height:1.7}.hact{display:flex;gap:12px;justify-content:center;flex-wrap:wrap}.hst{display:flex;gap:40px;justify-content:center;margin-top:36px;padding-top:28px;border-top:1px solid rgba(77,120,255,0.06)}.hs{text-align:center}.hn{font-size:24px;font-weight:700;color:var(--primary)}.hl{font-size:11.5px;color:var(--t3);margin-top:2px}.sh{position:absolute;bottom:36px;left:50%;transform:translateX(-50%);display:flex;flex-direction:column;align-items:center;gap:8px;font-size:11px;color:var(--t3);opacity:0;animation:fu .5s ease .9s forwards}.sa{width:20px;height:20px;border-right:1.5px solid var(--t3);border-bottom:1.5px solid var(--t3);transform:rotate(45deg);animation:bn 2s ease-in-out infinite}@keyframes bn{0%,100%{transform:rotate(45deg) translateY(0)}50%{transform:rotate(45deg) translateY(6px)}}
.sec{padding:64px 0;position:relative;z-index:1}.sh2{text-align:center;margin-bottom:36px}.sh2 h2{font-size:22px;font-weight:700;letter-spacing:.5px;margin-bottom:6px}.sh2 p{font-size:13.5px;color:var(--t2)}
.cg{display:grid;grid-template-columns:repeat(auto-fill,minmax(230px,1fr));gap:14px;max-width:820px;margin:0 auto}.ccr{display:flex;align-items:center;gap:14px;padding:18px 20px;text-decoration:none;transition:transform .2s}.ccr:hover{transform:translateY(-2px)}.cdt{width:38px;height:38px;border-radius:10px;display:flex;align-items:center;justify-content:center;flex-shrink:0}.cdi{width:12px;height:12px;border-radius:50%}.cdn{font-size:14px;font-weight:600;color:var(--t1)}.cdc{font-size:11.5px;color:var(--t3);margin-top:1px}
.ap{padding-top:96px;padding-bottom:60px}.bl{display:inline-flex;align-items:center;gap:6px;font-size:12.5px;color:var(--t3);text-decoration:none;margin-bottom:28px;transition:color .2s;opacity:0;animation:fu .4s cubic-bezier(.16,1,.3,1) forwards}.bl:hover{color:var(--primary)}.ah{text-align:center;margin-bottom:32px;opacity:0;animation:fu .45s cubic-bezier(.16,1,.3,1) .05s forwards}.ah h1{font-size:28px;font-weight:700;letter-spacing:.5px;line-height:1.4;margin-bottom:14px;max-width:700px;margin-left:auto;margin-right:auto}.am{font-size:12.5px;color:var(--t3);display:flex;align-items:center;justify-content:center;gap:12px;flex-wrap:wrap}.am .dt{width:3px;height:3px;border-radius:50%;background:var(--t3)}.acv{max-width:860px;margin:0 auto 32px;border-radius:var(--rl);overflow:hidden;opacity:0;animation:fu .5s cubic-bezier(.16,1,.3,1) .1s forwards}.acv img{width:100%;display:block}.abody{max-width:720px;margin:0 auto;padding:40px;font-size:14.5px;line-height:1.9;color:var(--t1);opacity:0;animation:fu .5s cubic-bezier(.16,1,.3,1) .15s forwards}.abody h2{font-size:20px;font-weight:700;margin:36px 0 14px}.abody h3{font-size:17px;font-weight:600;margin:28px 0 10px}.abody p{margin-bottom:16px}.abody ul,.abody ol{margin:12px 0 16px 20px}.abody li{margin-bottom:6px}.abody blockquote{margin:20px 0;padding:16px 20px;border-left:3px solid var(--primary);background:rgba(59,110,245,0.04);border-radius:0 var(--rm) var(--rm) 0;color:var(--t2);font-style:italic}.abody pre{margin:16px 0;padding:16px 20px;background:rgba(26,29,46,0.04);border-radius:var(--rm);overflow-x:auto;font-size:13px;line-height:1.6;font-family:'DM Mono','SF Mono','Menlo',monospace}.abody code{font-family:'DM Mono','SF Mono','Menlo',monospace;font-size:13px;background:rgba(59,110,245,0.06);padding:2px 6px;border-radius:4px}.abody pre code{background:none;padding:0}.abody img{max-width:100%;border-radius:var(--rm);margin:16px 0}.abody a{color:var(--primary);text-decoration:underline;text-underline-offset:2px}
.sg{display:grid;grid-template-columns:repeat(auto-fill,minmax(320px,1fr));gap:24px}.scv{aspect-ratio:16/10;overflow:hidden}.scv img{width:100%;height:100%;object-fit:cover;transition:transform .4s}.pc:hover .scv img{transform:scale(1.04)}.sb{padding:20px}.st2{font-size:16px;font-weight:700;margin-bottom:6px}.st2 a{color:var(--t1);text-decoration:none;transition:color .2s}.st2 a:hover{color:var(--primary)}.sd{font-size:13px;color:var(--t2);margin-bottom:12px;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.slk{font-size:12px;font-weight:600;color:var(--primary);text-decoration:none;display:inline-flex;align-items:center;gap:4px;transition:gap .2s}.slk:hover{gap:8px}
.abt{padding-top:96px;padding-bottom:60px}.abc{max-width:660px;margin:0 auto;padding:44px;text-align:center}.abig{width:96px;height:96px;border-radius:50%;margin:0 auto 24px;background:linear-gradient(135deg,var(--primary),var(--primary-light));display:flex;align-items:center;justify-content:center;font-size:40px;color:#fff;font-weight:700;border:3px solid rgba(255,255,255,0.8);box-shadow:0 6px 24px rgba(59,110,245,0.15)}.abc h1{font-size:24px;font-weight:700;margin-bottom:6px;letter-spacing:.5px}.arole{font-size:13px;color:var(--primary);font-weight:600;margin-bottom:20px}.abio{font-size:14px;color:var(--t2);line-height:1.85;margin-bottom:28px;text-align:left}.asc{display:flex;gap:10px;justify-content:center;flex-wrap:wrap}.asc a{display:inline-flex;align-items:center;gap:6px;padding:8px 18px;font-size:12.5px;font-weight:500;border-radius:var(--rp);color:var(--t2);background:rgba(255,255,255,0.3);border:1px solid rgba(77,120,255,0.06);text-decoration:none;transition:all .2s;backdrop-filter:blur(8px)}.asc a:hover{background:rgba(59,110,245,0.08);color:var(--primary)}
.rl a{display:flex;align-items:center;justify-content:space-between;padding:14px 20px;margin-bottom:10px;text-decoration:none;transition:transform .2s}.rl a:hover{transform:translateX(4px)}.rt{font-size:13.5px;font-weight:600;color:var(--t1)}.rd{font-size:11.5px;color:var(--t3)}
.wp{padding-top:96px;padding-bottom:60px}.wf{max-width:640px;margin:0 auto 32px;padding:32px}.wf h2{font-size:20px;font-weight:700;letter-spacing:.5px;margin-bottom:4px}.wf .su2{font-size:13px;color:var(--t2);margin-bottom:24px}.wr{display:flex;gap:10px;align-items:start;margin-bottom:14px}.wr input[type=text]{width:140px;flex-shrink:0}.wr textarea{flex:1;min-height:60px}.wtp{display:flex;gap:6px;margin-bottom:16px}.wtp label{display:flex;align-items:center;gap:5px;padding:6px 16px;font-size:12.5px;font-weight:500;border:1px solid rgba(77,120,255,0.06);border-radius:var(--rp);background:rgba(255,255,255,0.3);cursor:pointer;transition:all .2s;font-family:inherit}.wtp input{display:none}.wtp input:checked+span{color:var(--primary)}.wtp label:has(input:checked){background:rgba(59,110,245,0.08);border-color:rgba(59,110,245,0.2)}
.wg{max-width:900px;margin:0 auto;display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:16px}.wc{padding:20px;transition:transform .2s;opacity:0;animation:ci .5s cubic-bezier(.16,1,.3,1) forwards}.wc:nth-child(2){animation-delay:.04s}.wc:nth-child(3){animation-delay:.08s}.wc:nth-child(4){animation-delay:.12s}.wc:nth-child(5){animation-delay:.16s}.wc:nth-child(6){animation-delay:.2s}.wc:hover{transform:translateY(-3px)}.wch{display:flex;align-items:center;gap:10px;margin-bottom:12px}.wav{width:36px;height:36px;border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:15px;font-weight:700;color:#fff;flex-shrink:0}.wnk{font-size:13.5px;font-weight:600;color:var(--t1)}.wtm{font-size:11px;color:var(--t3)}.wtb{font-size:10.5px;font-weight:600;padding:2px 8px;border-radius:var(--rp)}.wtb.message{background:rgba(59,110,245,0.08);color:var(--primary)}.wtb.wish{background:rgba(217,119,6,0.08);color:var(--wn)}.wct{font-size:13.5px;color:var(--t1);line-height:1.7}
.es{text-align:center;padding:60px 20px}.ei{font-size:48px;margin-bottom:16px;opacity:.25}.es h3{font-size:17px;font-weight:600;margin-bottom:8px;color:var(--t2)}.es p{font-size:13px;color:var(--t3)}
@keyframes fu{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:translateY(0)}}.fi{opacity:0;animation:fu .45s cubic-bezier(.16,1,.3,1) forwards}.fd1{animation-delay:.05s}.fd2{animation-delay:.1s}.fd3{animation-delay:.15s}.fd4{animation-delay:.2s}
.ctn{max-width:1200px;margin:0 auto;padding:0 24px}.ft{text-align:center;padding:40px 24px 32px;font-size:12px;color:var(--t3);position:relative;z-index:1}.ft a{color:var(--primary);text-decoration:none}.ft .icp{margin-top:6px}
@media(max-width:960px){.bg{grid-template-columns:repeat(2,1fr)}.bg .pc.ft{grid-column:span 2}}
@media(max-width:640px){.nav{padding:0 16px}.ns{display:none}.nl a{padding:6px 10px;font-size:12px}.bg{grid-template-columns:1fr;gap:16px}.bg .pc.ft{grid-column:span 1}.bg .pc.ft .cc{aspect-ratio:16/9}.hero{min-height:auto;padding:100px 20px 60px}.hero h1{font-size:22px}.hc{padding:32px 24px}.hst{gap:24px}.abody{padding:24px 20px;font-size:14px}.ah h1{font-size:22px}.abc{padding:28px 20px}.sg{grid-template-columns:1fr}.wg{grid-template-columns:1fr}.wr{flex-direction:column}.wr input[type=text]{width:100%}.ctn{padding:0 16px}}
</style></head><body>

<div class="atmo"><div class="orb o1"></div><div class="orb o2"></div><div class="orb o3"></div><div class="orb o4"></div></div>

<?php if ($page !== 'landing'): ?>
<nav class="nav" id="mn"><a href="<?=url('/')?>" class="nb"><span class="f">🐟</span><?=e($bn)?></a>
<div class="nl">
<a href="<?=url('blog')?>" class="<?=$page==='blog'?'ac':''?>">博客</a>
<a href="<?=url('sharing')?>" class="<?=$page==='sharing'?'ac':''?>">分享</a>
<a href="<?=url('wish')?>" class="<?=$page==='wish'?'ac':''?>">许愿墙</a>
<a href="<?=url('about')?>" class="<?=$page==='about'?'ac':''?>">关于</a>
</div>
<div class="ns"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>
<form action="<?=url('blog')?>" method="GET" style="display:inline"><input type="text" name="q" placeholder="搜索文章…" value="<?=e($q)?>"></form></div></nav>
<?php endif;?>

<div style="position:relative;z-index:1">
<?php switch ($page):

case 'landing': $ft = get_posts('all','published',null,3); $tot = count_posts(); $tv = get_total_views(); $shp = get_posts('sharing','published',null,3); ?>
<section class="hero"><div class="hc glass"><div class="ha">🐟</div><h1><?=e($bn)?></h1><p class="ht"><?=e($bt)?></p><div class="hact"><a href="<?=url('blog')?>" class="btn btn-p">开始摸鱼</a><a href="<?=url('about')?>" class="btn btn-g">了解我</a></div><div class="hst"><div class="hs"><div class="hn"><?=$tot?></div><div class="hl">篇文章</div></div><div class="hs"><div class="hn"><?=$tv?></div><div class="hl">次阅读</div></div><div class="hs"><div class="hn"><?=count($cats)?></div><div class="hl">个分类</div></div></div></div><div class="sh"><span>向下探索</span><div class="sa"></div></div></section>
<?php if(!empty($ft)):?><section class="sec"><div class="ctn"><div class="sh2"><h2>✦ 精选文章</h2><p>摸鱼时写的精华内容</p></div><div class="bg"><?php foreach($ft as $i=>$p):?><article class="pc <?=$i===0?'ft':''?>"><?php if($p['cover_image']):?><div class="cc"><img src="<?=UPLOAD_URL.'/'.e($p['cover_image'])?>" loading="lazy"></div><?php else:?><div class="cc"><div class="ccp">🐟</div></div><?php endif;?><div class="cb"><div class="cm"><?php if($p['cat_name']):?><span class="tag ts" style="background:<?=e($p['cat_color'])?>12;color:<?=e($p['cat_color'])?>"><?=e($p['cat_name'])?></span><?php endif;?><span style="font-size:11px;color:var(--t3)"><?=time_ago($p['published_at'])?></span></div><div class="ct"><a href="<?=url('post/'.$p['slug'])?>"><?=e($p['title'])?></a></div><p class="ce"><?=e(truncate($p['excerpt']?:$p['content'],$i===0?200:120))?></p><div class="cf"><span><?=e($an)?></span><span class="v"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg><?=$p['view_count']?></span></div></div></article><?php endforeach;?></div></div></section><?php endif;?>
<?php if(!empty($cats)):?><section class="sec"><div class="ctn"><div class="sh2"><h2>📂 内容分类</h2><p>按兴趣探索</p></div><div class="cg"><?php foreach($cats as $c):?><a href="<?=url('blog/'.$c['slug'])?>" class="ccr glass"><div class="cdt" style="background:<?=e($c['color'])?>12"><div class="cdi" style="background:<?=e($c['color'])?>"></div></div><div><div class="cdn"><?=e($c['name'])?></div><div class="cdc"><?=$c['post_count']?> 篇</div></div></a><?php endforeach;?></div></div></section><?php endif;?>
<?php if(!empty($shp)):?><section class="sec"><div class="ctn"><div class="sh2"><h2>🛠️ 最新分享</h2></div><div class="sg"><?php foreach($shp as $s):?><article class="pc"><?php if($s['cover_image']):?><div class="scv"><img src="<?=UPLOAD_URL.'/'.e($s['cover_image'])?>" loading="lazy"></div><?php else:?><div class="scv" style="background:linear-gradient(135deg,rgba(59,110,245,0.04),rgba(59,110,245,0.12));display:flex;align-items:center;justify-content:center;font-size:36px;color:rgba(59,110,245,0.15)">✦</div><?php endif;?><div class="sb"><div class="st2"><a href="<?=url('post/'.$s['slug'])?>"><?=e($s['title'])?></a></div><p class="sd"><?=e(truncate($s['excerpt']?:$s['content'],130))?></p><a href="<?=url('post/'.$s['slug'])?>" class="slk">查看详情 →</a></div></article><?php endforeach;?></div></div></section><?php endif;?>
<footer class="ft"><p>© <?=date('Y')?> <a href="<?=url('/')?>"><?=e($bn)?></a> · 认真工作是为了更好地摸鱼 🐟</p><?php if($icp):?><p class="icp"><?=e($icp)?></p><?php endif;?></footer><?php break;

case 'blog': $cid = null; $cn = ''; if ($cat) { foreach ($cats as $c) { if ($c['slug'] === $cat) { $cid = $c['id']; $cn = $c['name']; break; } } }
if ($q) { $lk = '%' . $q . '%'; $st = db()->prepare("SELECT p.*,c.name AS cat_name,c.slug AS cat_slug,c.color AS cat_color FROM posts p LEFT JOIN categories c ON p.category_id=c.id WHERE p.status='published' AND (p.title LIKE ? OR p.content LIKE ? OR p.excerpt LIKE ?) ORDER BY p.is_featured DESC,p.published_at DESC LIMIT $pp OFFSET $off"); $st->execute([$lk,$lk,$lk]); $posts = $st->fetchAll(); $tc = db()->prepare("SELECT COUNT(*) FROM posts WHERE status='published' AND (title LIKE ? OR content LIKE ? OR excerpt LIKE ?)"); $tc->execute([$lk,$lk,$lk]); $total = (int)$tc->fetchColumn(); }
else { $posts = get_posts('all','published',$cid,$pp,$off); $total = count_posts('published',$cid); }
$pgs = max(1, ceil($total / $pp)); $pb = $q ? url('blog').'?q='.urlencode($q) : ($cat ? url('blog/'.$cat) : url('blog')); $pm = $q ? 'q' : 'p'; $pt = $q ? '搜索：'.e($q) : ($cn ? e($cn) : '全部文章'); ?>
<section style="padding-top:96px;padding-bottom:60px" class="ctn"><div class="fi" style="margin-bottom:28px"><h1 style="font-size:24px;font-weight:700"><?=$pt?></h1><p style="font-size:13px;color:var(--t3);margin-top:4px"><?=$total?> 篇文章</p></div>
<div class="fb fi fd1"><a href="<?=url('blog')?>" class="fp <?=!$cat&&!$q?'ac':''?>">全部</a><?php foreach($cats as $c):?><a href="<?=url('blog/'.$c['slug'])?>" class="fp <?=$cat===$c['slug']?'ac':''?>"><?=e($c['name'])?></a><?php endforeach;?></div>
<?php if(empty($posts)):?><div class="es glass fi fd2"><div class="ei">🐟</div><h3><?=$q?'没有找到相关文章':'还没有文章'?></h3><p><?=$q?'换个关键词试试':'博主可能还在摸鱼'?></p></div>
<?php else:?><div class="bg"><?php foreach($posts as $p):?><article class="pc <?=$p['is_featured']?'ft':''?>"><?php if($p['cover_image']):?><div class="cc"><img src="<?=UPLOAD_URL.'/'.e($p['cover_image'])?>" loading="lazy"></div><?php else:?><div class="cc"><div class="ccp">🐟</div></div><?php endif;?><div class="cb"><div class="cm"><?php if($p['cat_name']):?><span class="tag ts" style="background:<?=e($p['cat_color'])?>12;color:<?=e($p['cat_color'])?>"><?=e($p['cat_name'])?></span><?php endif;?><span style="font-size:11px;color:var(--t3)"><?=time_ago($p['published_at'])?></span></div><div class="ct"><a href="<?=url('post/'.$p['slug'])?>"><?=e($p['title'])?></a></div><p class="ce"><?=e(truncate($p['excerpt']?:$p['content'],120))?></p><div class="cf"><span><?=e($an)?></span><span class="v"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg><?=$p['view_count']?></span></div></div></article><?php endforeach;?></div>
<?php if($pgs>1):?><div class="pg"><?php if($paged>1):?><a href="<?=$pm==='p'?$pb.'/page/'.($paged-1):$pb.'&p='.($paged-1)?>">←</a><?php endif;?><?php for($i=1;$i<=$pgs;$i++):?><?php if($i===$paged):?><span class="cur"><?=$i?></span><?php else:?><a href="<?=$pm==='p'?$pb.'/page/'.$i:$pb.'&p='.$i?>"><?=$i?></a><?php endif;?><?php endfor;?><?php if($paged<$pgs):?><a href="<?=$pm==='p'?$pb.'/page/'.($paged+1):$pb.'&p='.($paged+1)?>">→</a><?php endif;?></div><?php endif;?><?php endif;?></section>
<footer class="ft"><p>© <?=date('Y')?> <a href="<?=url('/')?>"><?=e($bn)?></a> · 认真工作是为了更好地摸鱼 🐟</p></footer><?php break;

case 'post': $p = get_post($slug); if (!$p) redirect(url('blog')); $wc = mb_strlen(strip_tags($p['content'])); $rt = max(1, ceil($wc / 500)); ?>
<section class="ap ctn"><a href="<?=url('blog')?>" class="bl">← 返回博客</a>
<div class="ah"><?php if($p['cat_name']):?><a href="<?=url('blog/'.$p['cat_slug'])?>" class="tag" style="background:<?=e($p['cat_color'])?>12;color:<?=e($p['cat_color'])?>;text-decoration:none;margin-bottom:14px;display:inline-block"><?=e($p['cat_name'])?></a><?php endif;?><h1><?=e($p['title'])?></h1><div class="am"><span><?=e($an)?></span><span class="dt"></span><span><?=date('Y年m月d日',strtotime($p['published_at']))?></span><span class="dt"></span><span>约 <?=$rt?> 分钟</span><span class="dt"></span><span><?=$p['view_count']?> 次阅读</span></div></div>
<?php if($p['cover_image']):?><div class="acv"><img src="<?=UPLOAD_URL.'/'.e($p['cover_image'])?>"></div><?php endif;?>
<div class="abody glass"><?=$p['content']?></div>
<div style="max-width:720px;margin:28px auto 0;display:flex;justify-content:space-between" class="fi fd4"><a href="<?=url('blog')?>" class="btn btn-g sm">← 返回列表</a><button class="btn btn-g sm" onclick="navigator.clipboard.writeText(location.href).then(()=>{this.textContent='已复制 ✓';setTimeout(()=>this.textContent='复制链接',2000)})">复制链接</button></div>
<?php $rel = db()->prepare("SELECT title,slug FROM posts WHERE status='published' AND id!=? AND category_id=? ORDER BY published_at DESC LIMIT 3"); $rel->execute([$p['id'],$p['category_id']]); $rel = $rel->fetchAll(); if (count($rel) < 2) { $rel = db()->prepare("SELECT title,slug FROM posts WHERE status='published' AND id!=? ORDER BY RAND() LIMIT 3"); $rel->execute([$p['id']]); $rel = $rel->fetchAll(); } if (!empty($rel)): ?>
<div style="max-width:720px;margin:36px auto 0" class="fi fd4"><h3 style="font-size:15px;font-weight:700;margin-bottom:16px">推荐阅读</h3><div style="display:grid;grid-template-columns:repeat(auto-fill,minmax(200px,1fr));gap:12px"><?php foreach($rel as $r):?><a href="<?=url('post/'.$r['slug'])?>" class="glass" style="padding:16px 18px;text-decoration:none;display:block;transition:transform .2s;font-size:13px;font-weight:600;color:var(--t1);line-height:1.5"><?=e($r['title'])?></a><?php endforeach;?></div></div><?php endif;?></section>
<footer class="ft"><p>© <?=date('Y')?> <a href="<?=url('/')?>"><?=e($bn)?></a> · 认真工作是为了更好地摸鱼 🐟</p></footer><?php break;

case 'sharing': $posts = get_posts('sharing','published',null,20,0); ?>
<section style="padding-top:96px;padding-bottom:60px" class="ctn"><div class="fi" style="margin-bottom:28px"><h1 style="font-size:24px;font-weight:700">个人分享</h1><p style="font-size:13px;color:var(--t3);margin-top:4px">项目、作品与创意展示</p></div>
<?php if(empty($posts)):?><div class="es glass fi"><div class="ei">🛠️</div><h3>暂无分享</h3><p>博主正在憋大招</p></div>
<?php else:?><div class="sg"><?php foreach($posts as $s):?><article class="pc"><?php if($s['cover_image']):?><div class="scv"><img src="<?=UPLOAD_URL.'/'.e($s['cover_image'])?>" loading="lazy"></div><?php else:?><div class="scv" style="background:linear-gradient(135deg,rgba(59,110,245,0.04),rgba(59,110,245,0.12));display:flex;align-items:center;justify-content:center;font-size:36px;color:rgba(59,110,245,0.15)">✦</div><?php endif;?><div class="sb"><?php if($s['cat_name']):?><span class="tag ts" style="background:<?=e($s['cat_color'])?>12;color:<?=e($s['cat_color'])?>;margin-bottom:10px"><?=e($s['cat_name'])?></span><?php endif;?><div class="st2"><a href="<?=url('post/'.$s['slug'])?>"><?=e($s['title'])?></a></div><p class="sd"><?=e(truncate($s['excerpt']?:$s['content'],140))?></p><a href="<?=url('post/'.$s['slug'])?>" class="slk">查看详情 →</a></div></article><?php endforeach;?></div><?php endif;?></section>
<footer class="ft"><p>© <?=date('Y')?> <a href="<?=url('/')?>"><?=e($bn)?></a> · 认真工作是为了更好地摸鱼 🐟</p></footer><?php break;

case 'about': $gh = setting('social_github'); $tw = setting('social_twitter'); $em = setting('social_email'); $rec = get_posts('all','published',null,6,0); ?>
<section class="abt ctn"><div class="abc glass fi"><div class="abig">🐟</div><h1><?=e($an)?></h1><p class="arole"><?=e($ar)?></p><div class="abio"><?=nl2br(e($ab))?></div><?php if($gh||$tw||$em):?><div class="asc"><?php if($gh):?><a href="<?=e($gh)?>" target="_blank" rel="noopener">GitHub →</a><?php endif;?><?php if($tw):?><a href="<?=e($tw)?>" target="_blank" rel="noopener">Twitter →</a><?php endif;?><?php if($em):?><a href="mailto:<?=e($em)?>">Email →</a><?php endif;?></div><?php endif;?></div>
<?php if(!empty($rec)):?><div style="max-width:660px;margin:24px auto 0" class="rl fi fd1"><h3 style="font-size:15px;font-weight:700;margin-bottom:16px;text-align:center">最近发布</h3><?php foreach($rec as $r):?><a href="<?=url('post/'.$r['slug'])?>" class="glass" style="border-radius:var(--rm)"><span class="rt"><?=e($r['title'])?></span><span class="rd"><?=time_ago($r['published_at'])?></span></a><?php endforeach;?></div><?php endif;?></section>
<footer class="ft"><p>© <?=date('Y')?> <a href="<?=url('/')?>"><?=e($bn)?></a> · 认真工作是为了更好地摸鱼 🐟</p></footer><?php break;

case 'wish': $we = intval(setting('wish_enabled','1')); ?>
<section class="wp ctn"><div style="text-align:center;margin-bottom:32px" class="fi"><h1 style="font-size:24px;font-weight:700">🐟 留言许愿墙</h1><p style="font-size:13px;color:var(--t3);margin-top:4px">写下你想说的话，或者许下一个心愿</p></div>
<?php if($we):?><div class="wf glass fi"><div class="wr"><input type="text" id="wn" placeholder="你的昵称" maxlength="20"><textarea id="wc" placeholder="写下你想说的…" maxlength="500" rows="2"></textarea></div><div class="wtp"><label><input type="radio" name="wt" value="message" checked><span>💬 留言</span></label><label><input type="radio" name="wt" value="wish"><span>⭐ 许愿</span></label></div><button class="btn btn-p" onclick="postW()" style="width:100%">发表</button></div>
<?php else:?><div class="glass fi" style="max-width:500px;margin:0 auto 24px;padding:24px;text-align:center"><p style="color:var(--t3)">留言功能暂未开放</p></div><?php endif;?>
<div class="wg" id="wg"><div style="grid-column:1/-1;text-align:center;padding:40px;color:var(--t3)">加载中…</div></div><div class="pg" id="wpg" style="margin-top:32px"></div></section>
<footer class="ft"><p>© <?=date('Y')?> <a href="<?=url('/')?>"><?=e($bn)?></a> · 认真工作是为了更好地摸鱼 🐟</p></footer>
<script>
var wP=1;loadW(1);
function loadW(p){wP=p;fetch('<?=url("api.php")?>?action=wish_list&page='+p).then(r=>r.json()).then(d=>{if(!d.success)return;var g=document.getElementById('wg'),w=d.data.wishes;if(!w.length){g.innerHTML='<div style="grid-column:1/-1;text-align:center;padding:40px"><div style="font-size:40px;opacity:.25;margin-bottom:12px">🐟</div><p style="color:var(--t3)">还没有留言，做第一个吧</p></div>';document.getElementById('wpg').innerHTML='';return;}
g.innerHTML=w.map(function(x,i){var tb=x.wish_type==='wish'?'<span class="wtb wish">⭐ 许愿</span>':'<span class="wtb message">💬 留言</span>';return '<div class="wc glass" style="animation-delay:'+(i*0.04)+'s"><div class="wch"><div class="wav" style="background:'+x.avatar_color+'">'+esc(x.nickname).charAt(0).toUpperCase()+'</div><div style="flex:1;min-width:0"><div style="display:flex;align-items:center;gap:6px"><span class="wnk">'+esc(x.nickname)+'</span>'+tb+'</div><div class="wtm">'+tAgo(x.created_at)+'</div></div></div><div class="wct">'+esc(x.content)+'</div></div>'}).join('');
var pg='';if(d.data.pages>1){if(p>1)pg+='<a href="javascript:loadW('+(p-1)+')">←</a>';for(var i=1;i<=d.data.pages;i++)pg+=i===p?'<span class="cur">'+i+'</span>':'<a href="javascript:loadW('+i+')">'+i+'</a>';if(p<d.data.pages)pg+='<a href="javascript:loadW('+(p+1)+')">→</a>';}document.getElementById('wpg').innerHTML=pg;})}
function postW(){var n=document.getElementById('wn').value.trim(),c=document.getElementById('wc').value.trim(),t=document.querySelector('input[name="wt"]:checked').value;if(!n)return alert('请输入昵称');if(!c)return alert('请输入内容');var fd=new FormData();fd.append('nickname',n);fd.append('content',c);fd.append('wish_type',t);fetch('<?=url("api.php")?>?action=wish_post',{method:'POST',body:fd}).then(r=>r.json()).then(d=>{if(d.success){document.getElementById('wc').value='';loadW(1);}else alert(d.error||'失败');});}
function esc(s){var d=document.createElement('div');d.textContent=s;return d.innerHTML;}
function tAgo(dt){var diff=Math.floor((Date.now()-new Date(dt.replace(' ','T')+(dt.indexOf('+')<0?'+08:00':'')).getTime())/1000);if(diff<60)return'刚刚';if(diff<3600)return Math.floor(diff/60)+' 分钟前';if(diff<86400)return Math.floor(diff/3600)+' 小时前';return Math.floor(diff/86400)+' 天前';}
</script><?php break;

default: redirect(url('/')); endswitch;?>
</div>
<script>var nav=document.getElementById('mn');if(nav){var tk=false;window.addEventListener('scroll',function(){if(!tk){requestAnimationFrame(function(){nav.classList.toggle('sc',window.scrollY>30);tk=false;});tk=true;}});}</script></body></html>
